dataset_config:
  workers: 2 #orj:16
  train_class: FormatDatas #Market1501 #Occluded_Duke #Market1501 PartialOrOccluded
  test_class: FormatData #FormatData
  root: /content/drive/MyDrive/PersonReID-YouReID/dataset
  train_name : [market1501,Duke_pcb,cuhk03_pcb]
  test_name : market1501 #msmt17_pcb  #market1501 Duke_pcb msmt17_pcb cuhk03_pcb
  part: train
  height: 384 #384
  width: 128
  batch_size: 16
  load_img_to_cash: 0
  least_image_per_class: 4
  sample_image_per_class: 4
  rnd_select_nid: 0  #default 0
  use_tf_sample: 1
  use_random_pad: 0
  mgn_style_aug: false
#  mode: val

optm_config:
  name: SGD
  mode: train
  weight_decay: 0.0005
  warmup_factor: 0.
  momentum: 0.9
  epochs: 200 #120 # orj: 80
  start_epoch: 0
  lr: 0.001 #dyn icin: 0.004 #orj: 0.00625 #0.00625  #128 0.05
  resume: ''

model_config:
  name: CACENET
  num_layers: resnet50
  margin: 0.5
  alpha: 0.9
#  split_bn: true
  use_non_local: true
  pool_type: gemm

with_flip: true


