dataset_config:
  workers: 2
  train_class: FormatData #Market1501 #Occluded_Duke #Market1501 PartialOrOccluded
  test_class: FormatData #FormatData
  root: /content/drive/MyDrive/PersonReID-YouReID-flz/dataset
  train_name : Duke_pcb #cuhk03_pcb Occluded_Duke
  test_name : Duke_pcb #cuhk03_pcb msmt17_pcb  #market1501 Duke_pcb msmt17_pcb cuhk03_pcb Occluded_Duke
  part: train
  height: 256 #384
  width: 128
  batch_size: 128
  load_img_to_cash: 0
  least_image_per_class: 4
  sample_image_per_class: 4
  rnd_select_nid: 0  #default 0
  use_tf_sample: 0
  use_random_pad: 0
  mgn_style_aug: false
#  mode: val

optm_config:
  name: SGD
  mode: train
  weight_decay: 0.0005
  warmup_factor: 0.
  momentum: 0.9
  epochs: 80 #120 #orj: 80
  start_epoch: 0
  lr: 0.05  #128 0.05
  resume: ''

model_config:
  name: Baseline
  num_layers: resnet50
  loss_type: ['softmax', 'labelsmooth', 'triplet'] #'softmax', 'labelsmooth', 'arcface' #orjinal
  margin: 0.5
  split_bn: true
#  use_non_local: true




